// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiFFmvvvLPJmGI-5t5VMz9Tu6cIFywVl0',
    appId: '1:12180107230:web:0716c1f677b672d366b74f',
    messagingSenderId: '12180107230',
    projectId: 'app-6996b',
    authDomain: 'app-6996b.firebaseapp.com',
    storageBucket: 'app-6996b.firebasestorage.app',
    measurementId: 'G-1MXRVGHKTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF6A_XUaiBaSoyNVRItaqN7dtAXQSNiuI',
    appId: '1:12180107230:android:a049a1e0d3ac9cc466b74f',
    messagingSenderId: '12180107230',
    projectId: 'app-6996b',
    storageBucket: 'app-6996b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlv91qN7vlhjYRd0YC7Fn1Pf8utmZgsRA',
    appId: '1:12180107230:ios:23697916519a28e966b74f',
    messagingSenderId: '12180107230',
    projectId: 'app-6996b',
    storageBucket: 'app-6996b.firebasestorage.app',
    iosBundleId: 'com.example.secureLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlv91qN7vlhjYRd0YC7Fn1Pf8utmZgsRA',
    appId: '1:12180107230:ios:23697916519a28e966b74f',
    messagingSenderId: '12180107230',
    projectId: 'app-6996b',
    storageBucket: 'app-6996b.firebasestorage.app',
    iosBundleId: 'com.example.secureLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiFFmvvvLPJmGI-5t5VMz9Tu6cIFywVl0',
    appId: '1:12180107230:web:65aa2d94ff9bfb8266b74f',
    messagingSenderId: '12180107230',
    projectId: 'app-6996b',
    authDomain: 'app-6996b.firebaseapp.com',
    storageBucket: 'app-6996b.firebasestorage.app',
    measurementId: 'G-H46BQL6Z4R',
  );
}
